"""Sections + tables + figures -> Word -> (optionally) PDF. Generalised from the zinc-air
compiler. Resolves citation markers with resolve.py, substitutes {{T:key}} / {{F:key}}
references, appends the reference list, and writes the AI-assistance declaration that
verify.py refuses to let anyone remove.

Section files live in sections/ as SECTION_*.md and use the marker syntax:
    a claim  **[-> *Exact or near title of a corpus paper*]**   ->  resolves to a number
    see {{T:mytable}} / Figure {{F:myfigure}}                   ->  numbered in doc order
"""
from __future__ import annotations
import json, re
from pathlib import Path
from .resolve import resolve_markers

MARK = re.compile(r"→\s*\*([^*]+)\*|->\s*\*([^*]+)\*")


def _markers_in(sections):
    out = []
    for body in sections:
        for m in MARK.finditer(body):
            key = re.sub(r"\s+", " ", (m.group(1) or m.group(2))).strip()
            if key not in out:
                out.append(key)
    return out


def build(cfg, project: Path):
    project = Path(project)
    secs = sorted((project / "sections").glob("SECTION_*.md"))
    bodies = [s.read_text(encoding="utf-8").split("## Editorial notes")[0] for s in secs]

    # citation metadata: prefer harvested records; titles drive resolution
    recs_path = project / "corpus" / "harvest_records.json"
    recs = json.loads(recs_path.read_text(encoding="utf-8")) if recs_path.exists() else []
    titles = [r.get("title", "") for r in recs]

    markers = _markers_in(bodies)
    mapping, order, diags = resolve_markers(markers, titles)
    (project / "analysis").mkdir(exist_ok=True)
    (project / "analysis" / "resolve_diag.json").write_text(
        json.dumps(diags, indent=1, ensure_ascii=False), encoding="utf-8")

    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
    except ImportError:
        raise SystemExit("python-docx is required: pip install python-docx")

    doc = Document()
    if cfg.title:
        doc.add_heading(cfg.title, 0)
    if cfg.authors:
        doc.add_paragraph("; ".join(cfg.authors))
    if cfg.affiliation:
        doc.add_paragraph(cfg.affiliation)

    def resolve_text(t):
        def one(m):
            key = re.sub(r"\s+", " ", (m.group(1) or m.group(2))).strip()
            n = mapping.get(key)
            return f"[{n}]" if n else ""
        t = re.sub(r"\*\*\[[^\]]*(?:→|->)[^\]]*\]\*\*",
                   lambda mm: "[" + ",".join(str(mapping[k]) for k in _markers_in([mm.group(0)])
                                             if k in mapping) + "]", t)
        t = MARK.sub(one, t)
        # ACS placement: number outside punctuation
        t = re.sub(r"\s*(\[\d[\d,\-]*\])\s*([.,;:])", r"\2\1", t)
        return t

    for s, body in zip(secs, bodies):
        for para in resolve_text(body).split("\n\n"):
            para = para.strip()
            if not para:
                continue
            if para.startswith("#"):
                lvl = min(para.count("#"), 3)
                doc.add_heading(para.lstrip("# ").strip(), lvl)
            else:
                doc.add_paragraph(para)

    # AI declaration — principle 8; verify.py checks it stays
    if cfg.llm.backend != "none":
        doc.add_heading("Declaration of AI-Assisted Technologies", 1)
        doc.add_paragraph(
            "This work used a language model as an analysis and drafting tool. Every "
            "numerical value is regenerated by a script in the data deposit and is "
            "reproducible from the corpus; the authors reviewed the outputs and take full "
            "responsibility for the content.")

    # reference list
    doc.add_heading("References", 1)
    for n, idx in enumerate(order, 1):
        if isinstance(idx, int) and idx < len(recs):
            r = recs[idx]
            doc.add_paragraph(f"({n}) {r.get('title','')}. {r.get('year','')}. "
                              f"DOI: {r.get('doi','')}")
        else:
            doc.add_paragraph(f"({n}) [manual reference: {idx}]")

    out = project / "output" / "review.docx"
    out.parent.mkdir(exist_ok=True)
    doc.save(out)
    return out
